---
editor_options: 
  markdown: 
    wrap: sentence
---

Il seguente lavoro ha l'obiettivo di mettere inpiedi un servizio di API robusto, scalabile e sicuro per estrarre dati che riguardano immobili italiani e non (il caso studio è Milano) e successivamente applicare tecniche di geostatistica Bayesiana attraverso una conveniente alternativa di stima chiamata INLA.
I dati originano da una popolare piattaforma internet di affitti e vendite, immobiliare.it, e sono estratti tramite delle funzioni di web scraping costruite apposistamente sul sito.
Lo scraper è ottimizzato sia sul lato server richiedendo *gentilemente* il permesso e imponendo un cadenza di richiesta fissa, sia sul lato cliente finale garantendo continuità di flusso di dati tramite la rotazione degli headers della richiesta e con scappatoie in caso di fallimento delle funzioni.
le funzioni di scraping sfruttano un workflow che combina un reverse engineer degli della mappa degli url e una ricerca ottimizzata per parole chiave.
Il Miglioramento rispetto a servizi analoghi passa attrverso la posibilità di selezione quali url sono da scrappare, e di consequenza quali dati si ricerca.
Un ulteriore spinta è offerta dal parallelismo tramite cui vengono eseguite le funzioni applicando gli ultimi paradigmi dfi parallelismo e back end.
Alcuni test dimostrano la velocità della API per più configurazioni di scraping per più backend, oper più iteratori.
Il sietma di scraping è quindi avvolto attraverso un framework in R di API chiamato Plumber che permette di convertire il codice in http API decorandolo con speciali commenti.
La sicurezza è un tema di grande importanza per ogni interlocutore, pertanto semplici strategie di antidossing, comunicazione https e igiene dell'input del client sono trattatere e singolaremente applicate.\
Docker è in grado di impacchettare software in unità standardizzate per sviluppo portabilità e messa in produzione del servizio.
Quindi il servizio complessivo di API è containerizzato attraverso 3 diverse unità di servizi per cui dockerfiles su misura sono importati da una stessa matrice afferente ad una collabrazione open source tra docker e Rstudio, [Rocker](https://www.rocker-project.org/).
Le unità di servizi sono orchestrate da un'altra tecnologia di docker chiamata Compose attraverso un file di sitruzione .yaml.
Un server amazon EC2 è un prodotto cloud stabile scalabile che opsita l'infrastruttura software sopra descritta.
La scelta per criteri di economicità ed ispirazione open source ricade su una macchina server free-tier, cioò gratuia entro certi limiti di memoria e traffico.
All'interno dell'infratturura server l'api opita NGINX che opera come un autenticatore e centro di distribzione del traffico dell'api.
La capacità di oad balacing permette di amministrare diverse richieste simultanee non perdendo i requisiti di prestazione.
I principi architetturali di software applicati all'api da http la elevano ad essere RESTful.
la api rispetto all'obiettivo fissato non è altro che un mezzo di comunicazione tra due servizi inteernet tale per cui nessuno dei due attori, il cliente ed il server richiesto, debba sapere cosa è necessario (lo scraping) per ottenere i dati.
In altre parole ogni stakeholder può estrarre dati freschi da una comoda interfaccia che permette di flettere la richiesta solamente al tipo di dati richiesti e che rispetta la lista dei *desiderata* di sicurezza e prestaszione.
L'architettura software è amministrata tramite un workflow di sontinuo sviluppo e continua distribuzione (CI/CD) che sfrutta guithub e Dockerhub.
I cambiamenti nella cartella di github nel ramo master innescano il building dei contenitori tramite compose nella cartella cloud di dockerhub.
Successivamente il softwrae viene spinto dentro il server EC2 e quindi man mano aggiornato.
Quando la struttura è in piedi ogni dato disponibilr su immobiliare di ogni città, come da documentazione, può essere accesso; nel caso della seguente analisi i dati vengono in maniera asincrona da il mercato immobiliare delgi affitti a milano , restringendosi ai confini comunali.
I dati estratti contengono una componente gesospaziale nella forma di latitudine e longitudine, pertanto specifiche tecniche di analisi spaziale nel contesto bayesiano vengono utilizzate.
Tradizionalemente i methodi bayesiani nei contesti spaziali con big data sono lenti per motivi riconducibili all'invesrioni di gradi e dense matrici ceh impiegano un tempo cubico.
A proposito INLA, il cui acronimo sta per Integrated nested Laplace approximation è un algoritmo deterrministico che costituisce un 'alternativa più veloce e relativamente accurata di stima applicabile ad un tipo di modello detto LGM latent gaussian model.

Inla permette di ridurre il tempo di stima del modello grazie a approssiamzioni con laplace e ,metodi numerici per matrici sparse con lo scopo di avere le distrribuzioni a posteriori dei parametri e degli iper parametri.
I modelli edonici di prezzo costituiscono invece le basi teopriche sotto il profilo economico che sostengono la dinamica con cui i prezzi delle case, degli affitti in questo caso dipendono dalle covariate estratte, quindi la costruzione del predittore lineare.
Come da letteratura in materia i prezzi sono relazionalti al porezzo risultate dall'incontro tra domanda ed offerta di ogni caratteristica afferete alla casa, comprese quelle di natura gestostatistica.
Un aspetto ulteriore della question riguarda la non perfetta sovrapponibilità delle dinamiche che reegolano il prezzo delkl'immobili contro il prezo dell'affitto dello stesso, Gli accademici contestano questa assunzione, cionosotasnte l'evidenza emprica suggerisce che nel lungo periodo corrano di pari passo.
Tuttavia il nodo critico della questione spaziale non risiede nell'aspetto tecorico d'impostazione del modello, quanto nella stima come preannunciato.
quindi i modelli latenti gaussiani LGM vengono definiti e introdotti in un contesto gerarchico bayesiano con l'obiettivo di applicare inla.
Rispettivamente tre diffrentui livelli gerarchici sono individuati, il primo è la funzione di verosimiglianza dei dati (generalemnte una funzione pappartenente alla famiglia degli esponmenziali), un secondo livello detto GMRF, stante per gassuain mark9v random field ( doive risiedono gli obiettivi dell'inferenza), un terzo dove infine vengono attribuiti delle distribuzioni a priori per gli hyper parametri e per i parametri.
Il GMRF è un costrutto relativamente semplice, essendo una distribuzione multi normale centrata in 0 con matrice di precisone dipendende da qualche iper paramentro.
Cioò ceh lo rende markoviano è la sua struttura sparsa, tridiagonale, dovuta ad una assunzione di indipendenza condizioale sui parametri.
La componejnte spaziale dei dati è considerata come una realizzazione discreta di un porcesso Gaussiano GP non osservabile e continuo da stimare.
IL processo è comletamente caratterizzato da una struttura di media e da una matrice di covariaza, o analogamente una matrice di precisione .
Per il suddetto processo gaussiano sono fatte due importanti assunzioni: la staz\<inarietà e la isotropia, per le quali è possibile specificare una conveniente e flessbilee funzione di covariana detta Matèrn tipica degl ambti spaziali, della ecologia e della epidemiologia.
le soluzioni alle equazioni stocastiche e differenziali SPDE suggerisocno un rappresentazione gmrf di un processo spaziale gp la cui matrice di covaraianza è matern.
Questo succede grazie ad una rappresentazione trangolkarizzata della regione di studio detta mesh.
il modello è quinmdi fittato e cross validato con il pacchetto \>R-iNLA e due nuovi progetti open souce legati allo stesso BRINLA e inlabru a cuyra di ... Vengono quindi tirate le file estraendo i dati tramite l'api concernenti MIlano e fittato il modello tramite l'algoritmo inla.
I risulati sia delle performance e dell'ultizzo dell'api che del modello sono infine discussi.

## Ringraziamenti {.unnumbered}

Prima di tutto è mio dovere ripagare il debito di fiducia alèprofessore della vedova, il quale paziente,mente mi ha seguit durante questo progetto lungo 6 mesi.
Mi ha incoraggiato a spingere il cuore oltre l'ostacolo alzando l'asticella sia sui temi che sulle tecnologie utilizzartye, rilanciando sempre le mie proposte e offerndomi nuovi spunti o metodi di approccio.
La nostra comunicazione seppur saltuaria è sempre stata trasparente e dirtta al punto, e effiettivamet ogni monento speso è statop per me una lezione da cui imparare.
Sono giunto alla sua scrivania con idee forti e decise e ha avuto la mano e il polso di lasciarmi plasmare l'argomento come più ritenessi opportuno sotto il profilo della maotivazione personale e sotto il profilo enlle mie natruali inclinazioni per l'oggetto., In più seppur osassi più di quello che ci promettessimo di voltra in volta lui sai è sempre dimostrato aperto e felice doi aiutarmi a risolvbere novi problemi.

Devo tanto anche al dottor nardelli , è una delle persone più piavcevoli e preparate con cui abbia avuto la fortuna di collaborare.
Non posso negare di aver preso una grande ispirazione dal suo lavoro.
In tutta sincerità Vincenzo per me è stato apripista per tante cose, web scraping, la nostra nuova piattaforma Data Network, e infine la statistica spaziale.
I due pilastri su cui poggia la tesi si ispirano e poggiano sul suo lavoro, e per questo la sensazione è che lo stia indirettamente plagiando, ma ad un'analisi più seria non sfugge che sia soltanto ispirazione.

Devo molto anche alla professoressa lucia paci.
E' stata una delle migliori professoresse che abbia avuto il privilegio di incontrare.
Ha la straoridnaria capacità di decodificare concetti complessi e scomporli con precisione in semplici.
oltretutto le basi teroriche su cui ho costruito la tesi stanno in equulibrio sopra il suo lavoro e il suo materiale, uno dei quali lei è coautrice e costtiuisce è la maggiore referenza per questa analisi.

Non perderò l'occasione di ringraziare la mia fantastica ragazza elisabetta, è stata presente nei momenti più bui e ha visto le mie più nascoste insicurezza.
Tuttavia non ha esistato ad aiutarmi fin dal primo giorno che ci siamo conosciuti.
Con tutta certezza senza di lei niente di questo sarebbe stato possibile; è così intelligente e sensibile, e mi conosce così bene che quando ho avuto i miei momenti di sconforto, lei ha preso in mano la situazione nonostante le i suoi di problemi e loi ha risolti con l'unico trattamento sanitario obbligatorio che funziona con me, la schiacciata o il gelato.

Ringrazio anche mio babbo per essere una pietra miliare sia nella carriera che nella vita privata.
Mi ha sepmpre spinto ad insiguire i miei sogni e il mio inutito nonostante tutto, compreso il suo parere.
Il modo in cui ha condotto e conduce la sua vita è compimibile nella canzone di frank sinatra My way, e osservandolo nel suo lavoro, spero che il destino mi benedica con la sua indipendenza e libertà.

Speciali ringraziamenti sono dedicati ai miei zii, la zia iolanda e lo zio luciano.
Entrambi mi hanno sempre appoggiato facendomi sentire speciale e telntuoso nonostante l'università non mi abbia mai permesso di esprimere le mie velleità.
Il rapporto tra me e lo zio luciano è intenso e le nostre conversazioni sono sempre ispirazionali, per me è una stella polare, è qualcuno verso cui tendere, una bussola che indica la via da seguire, ma allo stesso tempo un astro luminoso da osservare, con tanto rispetto e timore reverenziale.
Lo zio è il più talentuoso businessman che ritengo avrò mai la fortuna di incotnrare, non passa un solo giorno in cui non speri di essere benedetto da 1 decimo del suo talento.
Non mi stancherò di dire che quello che ho fatto e che faccio èè uyna diretta conseguenza del suo successo, dei suoi sacrifici che ho avuto la fortuna di ascoltare e della sua guida.

Zia iolanda mi ha reso indietro una delle cose più importani che ci sono, la famiglia, Tu zia non hai mai amncato i momenti difficili, quelli che contano per davvero.
Hai sostenuto la mia mamma durante tutto il nostro esauriente percorso e noin finirò mai di ringraziarti per questo.
Sei davvero un angelo.

A tutti i miei anmici un grazie indistinto ma vitale per la vostra spinta.
Sfortunbatamente mi sto dilungando ma confido che in tempi milgiori una festa mi permetta di condividere il mio tragurdo con tutti voi, e in quel momento un pezzo di carta e tante lacrime faranno giustizia alla ia mancanza.

## Dedica {.unnumbered}

Alla mia amata mamma cristina, Lei ha fatto così tanto per me che nessuno se lo può immaginare.
Abbiamo affroinatnto momenti oggettivamente molto duri, fuoco e fiamme per un pop' di tempo er guarda dove siamo mamma, guada dovbe siamo arrivati.
E davvero faccio fatica a spiegare la sua forza, e se ... Ho senmpre penszato che le ,mamma avessero dei super poteri, ma credimi lettore mia mamma esagera.
Il nostro rapporto fatto di due caratteri molto forti e simili per la natura delle cose non è mai stato semplice e banale.
Quello che ci distringue dal resto del mondo credo sia la capacità di perseverare nel trovare un punto di equilibrio, un baricentro di sentimenti che sembra non poter stare in piedi, ma francamente mamma, a noi non interessa, noi persistiamo, siamo abituati a provarci, sempre.
Questo tratto ci rende inseparabili, perchè nonostante il mondo possa crollare tu sei sicura che farò quello ceh è nelle mie possibilità e oltre per avvicinarmi, e tu farai lo stesso.

Ripensando a tutto quello che ho fatto fin da quando ho una coscienza è tutto orientato a te alla tua soddisfazione, e in tutta onestà non me ne pento e non me ne pentirò.
tu sei la mia ispirazione e mi auguro un giorno di essere alla tua altezza.
Mamma sei andata all in in tutti sensi mandandomi a Milano e hai avuto ragione, le mamme hanno sempre ragione.

Tuo Niccolò.

*keywords* : Bayesian Statistics, RESTful API, Docker, AWS, INLA, Real Estate, Web Scraping, Parallel Computing, Hierarchical models.
